import os
import sys
import time
import pandas as pd
from datetime import datetime

# --- SENIOR ARCHITECTURE: DYNAMIC PATH INJECTION ---
# This forces Python to look in the local directory first.
current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.insert(0, current_dir)

# Professional Import Handling
try:
    # We import the function directly since the file is in the same directory
    from anomaly_detector import detect_anomalies
except ImportError as e:
    print(f"❌ Dependency Error: {e}")
    print(f"Ensure anomaly_detector.py is in: {current_dir}")
    sys.exit(1)

# --- BUSINESS LOGIC CONSTANTS (Flutter JD Alignment) ---
OPEX_SAVINGS_PER_TX = 1.25  # Strategic ROI Metric

def generate_stakeholder_report(start_time):
    """
    JD Requirement: 'Delivers performance reports for stakeholders'
    """
    try:
        # Use Absolute Paths to prevent 'Blank' output or File Not Found errors
        input_path = os.path.join(current_dir, "data", "input", "transactions.xlsx")
        output_path = os.path.join(current_dir, "data", "output", "flagged_transactions.xlsx")

        if not os.path.exists(input_path):
            print(f"⚠️  Report Skipped: Source data not found at {input_path}")
            return

        input_df = pd.read_excel(input_path, engine="openpyxl")
        
        # We check the output file generated by the anomaly_detector
        if os.path.exists(output_path):
            flagged_df = pd.read_excel(output_path, engine="openpyxl")
            anomalies = len(flagged_df)
        else:
            anomalies = 0

        total = len(input_df)
        savings = total * OPEX_SAVINGS_PER_TX

        print("\n" + "█"*60)
        print(f" SENTINEL CORE v2.2 | FINANCIAL INTEGRITY EXECUTIVE REPORT")
        print("█"*65)
        print(f" STATUS:            SUCCESSFUL")
        print(f" BATCH VOLUME:      {total} Transactions")
        print(f" ANOMALIES FOUND:   {anomalies} (Flagged for RPA)")
        print(f" ESTIMATED ROI:     £{savings:,.2f}")
        print(f" ENGINE LATENCY:    {time.time() - start_time:.4f}s")
        print("█"*65 + "\n")
        
    except Exception as e:
        print(f"⚠️  Metrics generation failed: {e}")

def main():
    start_time = time.time()
    print(f"--- [INITIALIZING RECONCILIATION ENGINE | {datetime.now().strftime('%H:%M:%S')}] ---")

    try:
        # 1. Execute Core Logic
        detect_anomalies()

        # 2. Generate BA Reporting
        generate_stakeholder_report(start_time)

        print("--- Process Complete ---")
        # Keeps terminal open for you to read the results
        input("\nPress Enter to exit...") 

    except Exception as e:
        print(f"❌ System Exception: {str(e)}")
        input("\nPress Enter to exit...")

if __name__ == "__main__":
    main()
